language: go

go:
  - stable
  - master

install:
  - go get -t -v ./...

script:
  - go test -v -count=1 tests/* && golint . ./interceptors/ ./internal/ ./tests/

after_success:
  - bash <(curl -s https://codecov.io/bash)